### ISSUE TITLE
Add changes and fixes from svn repository version [r145] 

### ISSUE THREAD

**Issue by bugcrazy** [aggeom/agg-2.6#11]
Version [r140] to [r145] has a lot of fixes and improvements:

https://sourceforge.net/p/agg/svn/140/

https://sourceforge.net/p/agg/svn/141/

https://sourceforge.net/p/agg/svn/143/

https://sourceforge.net/p/agg/svn/145/

**Comment by xakod** [comment]
Thank you! I'll add it soon
