### ISSUE TITLE
Add changes and fixes from svn repository version [r138] to your repository

### ISSUE THREAD

**Issue by bugcrazy** [aggeom/agg-2.6#6]
These are fixes and file changes made until 2021, your repository does not have these fixes, as it is based on the [R132] version of 2018: https://sourceforge.net/p/agg/svn/commit_browser

**Comment by Jihadist** [comment]
@bugcrazy thank you, I did not look at svn repo

**Comment by bugcrazy** [comment]
The Zardshard patch has important fixes for AGG:
https://github.com/aggeom/agg-2.6/pull/7
